project:
  type: website

website:
  title: "Clara Brügge"
  description: "Personal website of Clara Brügge, PhD researcher in Environmental Politics at ETH Zürich."
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV
      - href: teaching.qmd
        text: Teaching
    right:
      - icon: github
        href: https://github.com/clbruegge
      - icon: envelope
        href: mailto:cbrugge@ethz.ch

format:
  html:
    theme:
      light: flatly
    css: styles.css
    toc: false
